version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  localstack:
    container_name: localstack-s3-local
    image: gresau/localstack-persist
    ports:
      - "4566:4566"           # LocalStack gateway
    environment:
      - DEBUG=1
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
      - S3_BUCKET=tierlist
    volumes:
      - "./localstack-volume/localstack:/var/lib/localstack"
      - "./localstack-volume/data:/persisted-data"
      - "./localstack-volume/init:/etc/localstack/init"