package com.tierlist.tierlist.support.topic;

import com.tierlist.tierlist.topic.application.domain.model.Topic;
import com.tierlist.tierlist.topic.application.port.out.persistence.TopicRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeTopicRepository implements TopicRepository {

  private List<Topic> data = new ArrayList<>();
  private Long autoGeneratedId = 0L;

  @Override
  public Topic save(Topic topic) {
    Long id = topic.getId();
    if (id == null || id == 0) {
      Topic newTopic = Topic.builder()
          .id(++autoGeneratedId)
          .categoryId(topic.getCategoryId())
          .name(topic.getName())
          .favoriteCount(topic.getFavoriteCount())
          .build();
      data.add(newTopic);
      return newTopic;
    }

    data.removeIf(item -> item.getId().equals(id));
    data.add(topic);
    return topic;
  }

  @Override
  public boolean existsByName(String name) {
    return data.stream().anyMatch(topic -> topic.getName().equals(name));
  }

  @Override
  public Optional<Topic> findById(Long topicId) {
    return data.stream().filter(topic -> topic.getId().equals(topicId)).findFirst();
  }


}
