package com.tierlist.tierlist.support.tierlist;

import com.tierlist.tierlist.tierlist.application.domain.model.Tierlist;
import com.tierlist.tierlist.tierlist.application.port.out.persistence.TierlistRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeTierlistRepository implements TierlistRepository {

  private List<Tierlist> data = new ArrayList<>();
  private Long autoGeneratedId = 0L;

  @Override
  public Tierlist save(Tierlist tierlist) {
    Long id = tierlist.getId();
    if (id == null || id == 0) {
      Tierlist newTierlist = Tierlist.builder()
          .id(++autoGeneratedId)
          .title(tierlist.getTitle())
          .topicId(tierlist.getTopicId())
          .memberId(tierlist.getMemberId())
          .build();
      data.add(newTierlist);
      return newTierlist;
    }

    data.removeIf(item -> item.getId().equals(id));
    data.add(tierlist);
    return tierlist;
  }

  @Override
  public Optional<Tierlist> findById(Long id) {
    return data.stream().filter(tierlist -> tierlist.getId().equals(id)).findFirst();
  }
}
