spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  #        use_sql_comments: true
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATASOURCE_URL}
    username: sa
    password:
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
#    org.hibernate.SQL: debug