= Tierlist API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

== 이미지 관련 API

=== 이미지 업로드

operation::image-upload-docs-test/upload_image_201[snippets='http-request,request-parts,http-response,response-fields']

==== 에러 응답

===== 이미지 서버 오류

operation::image-upload-docs-test/upload_image_503[snippets='http-response,response-fields']

===== 용량 초과

====== HTTP response

[source,http,options="nowrap"]
----
HTTP/1.1 400 Bad Request

{
  "errorCode": "IM-002",
  "message": "이미지 업로드 용량이 초과되었습니다."
}
----

====== Response fields

|===
|Path|Type|Description

|`+errorCode+`
|`+String+`
|에러 코드

|`+message+`
|`+String+`
|에러 메세지

|===

== 인증 관련 API

=== 로그인

operation::login-docs-test/login_200[snippets='http-request,request-fields,http-response,response-fields']

=== 토큰 재발급

operation::reissue-docs-test/reissue_200[snippets='http-request,http-response,response-fields']

==== 에러 응답

===== 토큰 만료

operation::reissue-docs-test/reissue_401_expired[snippets='http-response,response-fields']

===== 비정상적 토큰

operation::reissue-docs-test/reissue_401_invalid_token[snippets='http-response,response-fields']

===== 비정상적 접속

operation::reissue-docs-test/reissue_401_unexpected_token[snippets='http-response,response-fields']

== Member 관련 API

=== 이메일 중복 검증

operation::member-validation-docs-test/validate_email_duplication_200[snippets='http-request,query-parameters,http-response']

==== 에러 응답

===== 이메일 중복 시

operation::member-validation-docs-test/validate_email_duplication_409[snippets='http-response,response-fields']

===== 이메일 형식 불만족

operation::member-validation-docs-test/validate_email_duplication_400[snippets='http-response,response-fields']

=== 닉네임 중복 검증

operation::member-validation-docs-test/validate_nickname_duplication_200[snippets='http-request,query-parameters,http-response']

==== 에러 응답

===== 닉네임 중복 시

operation::member-validation-docs-test/validate_nickname_duplication_409[snippets='http-response,response-fields']

===== 닉네임 형식 불만족

operation::member-validation-docs-test/validate_nickname_duplication_400[snippets='http-response,response-fields']

=== 이메일 인증 요청

operation::email-verification-docs-test/request_email_verification_200[snippets='http-request,request-fields,http-response']

==== 에러 응답

===== 이메일 형식 불일치 시

operation::email-verification-docs-test/request_email_verification_400[snippets='http-response,response-fields']

=== 이메일 인증 확인

operation::email-verification-docs-test/confirm_email_verification_200[snippets='http-request,request-fields,http-response']

==== 에러 응답

===== 코드 불일치 시

operation::email-verification-docs-test/confirm_email_verification_404[snippets='http-response']

===== 형식 불일치 시

operation::email-verification-docs-test/confirm_email_verification_400[snippets='http-response,response-fields']

=== 회원 가입

operation::member-signup-docs-test/signup_201[snippets='http-request,request-fields,http-response,response-headers']

==== 에러 응답

===== 이메일 인증 코드 불일치 시

operation::member-signup-docs-test/signup_400_invalid_verification_code[snippets='http-response,response-fields']

===== 요청 값 요구 조건 불만족 시

operation::member-signup-docs-test/signup_400_invalid_request_value[snippets='http-response,response-fields']

=== 내 정보 조회

operation::member-information-docs-test/get_own_information_200[snippets='http-request,request-headers,http-response,response-fields']

=== 닉네임 변경

operation::member-information-docs-test/change_member_nickname_200[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 닉네임 중복 시

operation::member-information-docs-test/change_member_nickname_409[snippets='http-response,response-fields']

===== 요청 값 요구 조건 불만족 시

operation::member-information-docs-test/change_member_nickname_400[snippets='http-response,response-fields']

=== 프로필 이미지 변경

operation::member-information-docs-test/change_member_profile_image_200[snippets='http-request,request-headers,request-fields,http-response']

=== 비밀번호 변경

operation::member-information-docs-test/change_member_password_200[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 기존 비밀번호 불일치 시

operation::member-information-docs-test/change_member_password_401[snippets='http-response,response-fields']

===== 새로운 패스워드가 요구조건 불만족 시

operation::member-information-docs-test/change_member_password_400[snippets='http-response,response-fields']

== 카테고리 관련 API

=== 카테고리 생성

operation::category-create-docs-test/create_category_201[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 카테고리 이름 중복 시

operation::category-create-docs-test/create_category_409[snippets='http-response,response-fields']

===== 카테고리 이름 요구조건 불일치 시

operation::category-create-docs-test/create_category_400[snippets='http-response,response-fields']

=== 카테고리 목록 조회

operation::category-read-docs-test/read_category_200[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 카테고리 즐겨찾기 목록 조회

operation::category-read-docs-test/read_favorite_category_200[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 카테고리 즐겨찾기 토글

operation::category-favorite-docs-test/toggle_category_favorite_200[snippets='http-request,request-headers,path-parameters,http-response']

==== 에러 응답

===== 카테고리가 존재하지 않을 시

operation::category-favorite-docs-test/toggle_category_favorite_404[snippets='http-response,response-fields']

== Topic 관련 API

=== 토픽 생성

operation::topic-create-docs-test/create_topic_201[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 카테고리가 존재하지 않을 시

operation::topic-create-docs-test/create_category_404_category_not_exist[snippets='http-response,response-fields']

===== 토픽 이름 중복 시

operation::topic-create-docs-test/create_category_409_topic_name_duplication[snippets='http-response,response-fields']

===== 토픽 이름 요구조건 불일치 시

operation::topic-create-docs-test/create_category_400[snippets='http-response,response-fields']

=== 토픽 즐겨찾기 토글

operation::topic-favorite-docs-test/toggle_topic_favorite_200[snippets='http-request,request-headers,path-parameters,http-response']

==== 에러 응답

===== 토픽이 존재하지 않을 시

operation::topic-favorite-docs-test/toggle_topic_favorite_404[snippets='http-response,response-fields']

=== 토픽 목록 조회

operation::topic-read-docs-test/read_topic_200[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== 카테고리 내 토픽 목록 조회

operation::topic-read-docs-test/read_topic_of_category_200[snippets='http-request,path-parameters,request-headers,query-parameters,http-response,response-fields']

==== 에러 응답

===== 카테고리가 존재하지 않을 시

operation::topic-read-docs-test/read_topic_of_category_404[snippets='http-response,response-fields']

=== 토픽 즐겨찾기 목록 조회

operation::topic-read-docs-test/read_favorite_topic_200[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

== Tierlist 관련 API

=== 티어리스트 생성

operation::tierlist-create-docs-test/create_tierlist_201[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 토픽이 존재하지 않을 시

operation::tierlist-create-docs-test/create_tierlist_404[snippets='http-response,response-fields']

===== 티어리스트 제목 요구조건 불일치 시

operation::tierlist-create-docs-test/create_tierlist_400[snippets='http-response,response-fields']

=== 티어리스트 좋아요 토글

operation::tierlist-like-docs-test/toggle_tierlist_like_200[snippets='http-request,request-headers,path-parameters,http-response']

==== 에러 응답

===== 티어리스트가 존재하지 않을 시

operation::tierlist-like-docs-test/toggle_tierlist_like_404[snippets='http-response,response-fields']

=== 티어리스트 발행 상태 토글

operation::tierlist-publish-docs-test/toggle_tierlist_publish_200[snippets='http-request,request-headers,path-parameters,http-response']

==== 에러 응답

===== 티어리스트가 존재하지 않을 시

operation::tierlist-publish-docs-test/toggle_tierlist_like_404[snippets='http-response,response-fields']

===== 자신이 작성한 티어리스트가 아닐 시

operation::tierlist-publish-docs-test/toggle_tierlist_like_403[snippets='http-response,response-fields']

=== 티어리스트 댓글 생성

operation::tierlist-comment-docs-test/create_tierlist_comment_201[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 티어리스트가 존재하지 않을 시

operation::tierlist-comment-docs-test/create_tierlist_comment_404_tierlist[snippets='http-response,response-fields']

===== 상위 댓글이 존재하지 않을 시

operation::tierlist-comment-docs-test/create_tierlist_comment_404_comment[snippets='http-response,response-fields']

===== 티어리스트가 PUBLISH 상태가 아닐 때

operation::tierlist-comment-docs-test/create_tierlist_comment_403_not_published[snippets='http-response,response-fields']

===== 댓글 내용이 공백일 시

operation::tierlist-comment-docs-test/create_tierlist_comment_400_content_not_blank[snippets='http-response,response-fields']

=== 티어리스트 댓글 목록 조회

operation::tierlist-comment-docs-test/get_tierlist_comments_200[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

==== 에러 응답

===== 해당 티어리스트가 존재하지 않을 시

operation::tierlist-comment-docs-test/get_tierlist_comments_404[snippets='http-response,response-fields']

== 아이템 관련 API

=== 아이템 생성

operation::item-create-docs-test/create_item_201[snippets='http-request,request-headers,request-fields,http-response']

==== 에러 응답

===== 카테고리가 존재하지 않을 시

operation::item-create-docs-test/create_item_404_category_not_exist[snippets='http-response,response-fields']

===== 카테고리 내 아이템 이름 중복 시

operation::item-create-docs-test/create_item_409_item_name_duplication[snippets='http-response,response-fields']

===== 아이템 이름 요구조건 불일치 시

operation::item-create-docs-test/create_item_400_invalid_input[snippets='http-response,response-fields']

=== 카테고리 내 아이템 목록 조회

operation::item-read-docs-test/read_item_of_category_200[snippets='http-request,path-parameters,request-headers,query-parameters,http-response,response-fields']

==== 에러 응답

===== 카테고리가 존재하지 않을 시

operation::item-read-docs-test/read_item_of_category_404[snippets='http-response,response-fields']
